server:
  port: 8008
spring:
  cloud:
    gateway:
      routes:
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: third-party
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>/?.*), /$\{segment}

        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: renren-generator
          uri: lb://renren-generator
          predicates:
            - Path=/api/generator/**
          filters:
            - RewritePath=/api/generator(?<segment>/?.*), $\{segment}

        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast$\{segment}