server:
  port: 9050
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_wms?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password:
logging:
  level:
    com.joiller: debug